#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odevDeneme
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="futbolTasarimDesenleri")]
	public partial class EslemeTableDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserteslemTablo(eslemTablo instance);
    partial void UpdateeslemTablo(eslemTablo instance);
    partial void DeleteeslemTablo(eslemTablo instance);
    #endregion
		
		public EslemeTableDataClassesDataContext() : 
				base(global::odevDeneme.Properties.Settings.Default.futbolTasarimDesenleriConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EslemeTableDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EslemeTableDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EslemeTableDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EslemeTableDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<eslemTablo> eslemTablos
		{
			get
			{
				return this.GetTable<eslemTablo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.eslemTablo")]
	public partial class eslemTablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _sp1id;
		
		private int _sp2id;
		
		private int _hkid;
		
		private int _stid;
		
		private int _hk2id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsp1idChanging(int value);
    partial void Onsp1idChanged();
    partial void Onsp2idChanging(int value);
    partial void Onsp2idChanged();
    partial void OnhkidChanging(int value);
    partial void OnhkidChanged();
    partial void OnstidChanging(int value);
    partial void OnstidChanged();
    partial void Onhk2idChanging(int value);
    partial void Onhk2idChanged();
    #endregion
		
		public eslemTablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp1id", DbType="Int NOT NULL")]
		public int sp1id
		{
			get
			{
				return this._sp1id;
			}
			set
			{
				if ((this._sp1id != value))
				{
					this.Onsp1idChanging(value);
					this.SendPropertyChanging();
					this._sp1id = value;
					this.SendPropertyChanged("sp1id");
					this.Onsp1idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sp2id", DbType="Int NOT NULL")]
		public int sp2id
		{
			get
			{
				return this._sp2id;
			}
			set
			{
				if ((this._sp2id != value))
				{
					this.Onsp2idChanging(value);
					this.SendPropertyChanging();
					this._sp2id = value;
					this.SendPropertyChanged("sp2id");
					this.Onsp2idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hkid", DbType="Int NOT NULL")]
		public int hkid
		{
			get
			{
				return this._hkid;
			}
			set
			{
				if ((this._hkid != value))
				{
					this.OnhkidChanging(value);
					this.SendPropertyChanging();
					this._hkid = value;
					this.SendPropertyChanged("hkid");
					this.OnhkidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stid", DbType="Int NOT NULL")]
		public int stid
		{
			get
			{
				return this._stid;
			}
			set
			{
				if ((this._stid != value))
				{
					this.OnstidChanging(value);
					this.SendPropertyChanging();
					this._stid = value;
					this.SendPropertyChanged("stid");
					this.OnstidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hk2id", DbType="Int NOT NULL")]
		public int hk2id
		{
			get
			{
				return this._hk2id;
			}
			set
			{
				if ((this._hk2id != value))
				{
					this.Onhk2idChanging(value);
					this.SendPropertyChanging();
					this._hk2id = value;
					this.SendPropertyChanged("hk2id");
					this.Onhk2idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
