#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odevDeneme
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="futbolTasarimDesenleri")]
	public partial class hakemlerdbDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserthakemlerPenceresiDb(hakemlerPenceresiDb instance);
    partial void UpdatehakemlerPenceresiDb(hakemlerPenceresiDb instance);
    partial void DeletehakemlerPenceresiDb(hakemlerPenceresiDb instance);
    #endregion
		
		public hakemlerdbDataClassesDataContext() : 
				base(global::odevDeneme.Properties.Settings.Default.futbolTasarimDesenleriConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public hakemlerdbDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hakemlerdbDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hakemlerdbDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public hakemlerdbDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<hakemlerPenceresiDb> hakemlerPenceresiDbs
		{
			get
			{
				return this.GetTable<hakemlerPenceresiDb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hakemlerPenceresiDb")]
	public partial class hakemlerPenceresiDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _klasman;
		
		private string _bolge;
		
		private string _grup;
		
		private string _turu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnklasmanChanging(string value);
    partial void OnklasmanChanged();
    partial void OnbolgeChanging(string value);
    partial void OnbolgeChanged();
    partial void OngrupChanging(string value);
    partial void OngrupChanged();
    partial void OnturuChanging(string value);
    partial void OnturuChanged();
    #endregion
		
		public hakemlerPenceresiDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="NChar(20)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="NChar(15)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klasman", DbType="NChar(15)")]
		public string klasman
		{
			get
			{
				return this._klasman;
			}
			set
			{
				if ((this._klasman != value))
				{
					this.OnklasmanChanging(value);
					this.SendPropertyChanging();
					this._klasman = value;
					this.SendPropertyChanged("klasman");
					this.OnklasmanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bolge", DbType="NChar(15)")]
		public string bolge
		{
			get
			{
				return this._bolge;
			}
			set
			{
				if ((this._bolge != value))
				{
					this.OnbolgeChanging(value);
					this.SendPropertyChanging();
					this._bolge = value;
					this.SendPropertyChanged("bolge");
					this.OnbolgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grup", DbType="NChar(15)")]
		public string grup
		{
			get
			{
				return this._grup;
			}
			set
			{
				if ((this._grup != value))
				{
					this.OngrupChanging(value);
					this.SendPropertyChanging();
					this._grup = value;
					this.SendPropertyChanged("grup");
					this.OngrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turu", DbType="NChar(15)")]
		public string turu
		{
			get
			{
				return this._turu;
			}
			set
			{
				if ((this._turu != value))
				{
					this.OnturuChanging(value);
					this.SendPropertyChanging();
					this._turu = value;
					this.SendPropertyChanged("turu");
					this.OnturuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
