#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odevDeneme
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="futbolTasarimDesenleri")]
	public partial class islemDatabaseDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertislemBilgiDb(islemBilgiDb instance);
    partial void UpdateislemBilgiDb(islemBilgiDb instance);
    partial void DeleteislemBilgiDb(islemBilgiDb instance);
    #endregion
		
		public islemDatabaseDataClassesDataContext() : 
				base(global::odevDeneme.Properties.Settings.Default.futbolTasarimDesenleriConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public islemDatabaseDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public islemDatabaseDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public islemDatabaseDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public islemDatabaseDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<islemBilgiDb> islemBilgiDbs
		{
			get
			{
				return this.GetTable<islemBilgiDb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.islemBilgiDb")]
	public partial class islemBilgiDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _islem;
		
		private System.Nullable<System.DateTime> _zaman;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnislemChanging(string value);
    partial void OnislemChanged();
    partial void OnzamanChanging(System.Nullable<System.DateTime> value);
    partial void OnzamanChanged();
    #endregion
		
		public islemBilgiDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_islem", DbType="NVarChar(50)")]
		public string islem
		{
			get
			{
				return this._islem;
			}
			set
			{
				if ((this._islem != value))
				{
					this.OnislemChanging(value);
					this.SendPropertyChanging();
					this._islem = value;
					this.SendPropertyChanged("islem");
					this.OnislemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zaman", DbType="DateTime")]
		public System.Nullable<System.DateTime> zaman
		{
			get
			{
				return this._zaman;
			}
			set
			{
				if ((this._zaman != value))
				{
					this.OnzamanChanging(value);
					this.SendPropertyChanging();
					this._zaman = value;
					this.SendPropertyChanged("zaman");
					this.OnzamanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
