#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odevDeneme
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="futbolTasarimDesenleri")]
	public partial class sporcuDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertsporcuPenceresiDb(sporcuPenceresiDb instance);
    partial void UpdatesporcuPenceresiDb(sporcuPenceresiDb instance);
    partial void DeletesporcuPenceresiDb(sporcuPenceresiDb instance);
    #endregion
		
		public sporcuDataClassesDataContext() : 
				base(global::odevDeneme.Properties.Settings.Default.futbolTasarimDesenleriConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sporcuDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sporcuDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sporcuDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sporcuDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<sporcuPenceresiDb> sporcuPenceresiDbs
		{
			get
			{
				return this.GetTable<sporcuPenceresiDb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sporcuPenceresiDb")]
	public partial class sporcuPenceresiDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _adi;
		
		private string _soyadi;
		
		private string _ligi;
		
		private string _diger;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnadiChanging(string value);
    partial void OnadiChanged();
    partial void OnsoyadiChanging(string value);
    partial void OnsoyadiChanged();
    partial void OnligiChanging(string value);
    partial void OnligiChanged();
    partial void OndigerChanging(string value);
    partial void OndigerChanged();
    #endregion
		
		public sporcuPenceresiDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adi", DbType="NChar(15)")]
		public string adi
		{
			get
			{
				return this._adi;
			}
			set
			{
				if ((this._adi != value))
				{
					this.OnadiChanging(value);
					this.SendPropertyChanging();
					this._adi = value;
					this.SendPropertyChanged("adi");
					this.OnadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soyadi", DbType="NChar(15)")]
		public string soyadi
		{
			get
			{
				return this._soyadi;
			}
			set
			{
				if ((this._soyadi != value))
				{
					this.OnsoyadiChanging(value);
					this.SendPropertyChanging();
					this._soyadi = value;
					this.SendPropertyChanged("soyadi");
					this.OnsoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ligi", DbType="NChar(15)")]
		public string ligi
		{
			get
			{
				return this._ligi;
			}
			set
			{
				if ((this._ligi != value))
				{
					this.OnligiChanging(value);
					this.SendPropertyChanging();
					this._ligi = value;
					this.SendPropertyChanged("ligi");
					this.OnligiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diger", DbType="NChar(30)")]
		public string diger
		{
			get
			{
				return this._diger;
			}
			set
			{
				if ((this._diger != value))
				{
					this.OndigerChanging(value);
					this.SendPropertyChanging();
					this._diger = value;
					this.SendPropertyChanged("diger");
					this.OndigerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
